# Generated by Django 3.1 on 2021-01-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vpnuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=256, unique=True)),
                ('channel', models.CharField(choices=[('TG', 'Telegram'), ('EM', 'Email'), ('SG', 'Signal'), ('NA', 'Unknown')], default='NA', max_length=2)),
                ('reputation', models.IntegerField(default=0)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('banned', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutlineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('outline_key_id', models.IntegerField()),
                ('outline_key', models.CharField(max_length=512)),
                ('reputation', models.IntegerField(default=0)),
                ('transfer', models.FloatField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.outlineserver')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outline_keys', to='distribution.vpnuser')),
                ('user_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribution.issue')),
            ],
            options={
                'verbose_name': 'OutlineUser',
                'verbose_name_plural': 'OutlineUsers',
            },
        ),
    ]
