# Generated by Django 3.0.5 on 2020-07-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='outlineuser',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vpnuser',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
