# Generated by Django 3.1 on 2020-08-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_auto_20200724_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description_ar',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='description_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='description_fa',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
