# Generated by Django 3.1 on 2020-09-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_auto_20200818_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnuser',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
