# Generated by Django 3.1 on 2020-10-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_vpnuser_delete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnuser',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
