# Generated by Django 3.1 on 2021-01-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv6', models.GenericIPAddressField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=128, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('user_src', models.CharField(choices=[('TG', 'Telegram'), ('EM', 'Email'), ('SG', 'Signal'), ('NA', 'Unknows')], default='NA', max_length=2)),
                ('reputation', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('alert', models.BooleanField(default=False)),
                ('user_count', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_distributing', models.BooleanField(default=True)),
                ('api_url', models.TextField(blank=True, null=True)),
                ('api_cert', models.TextField(blank=True, null=True)),
                ('prometheus_port', models.IntegerField(default=900)),
                ('region', models.ManyToManyField(blank=True, to='preference.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
